version: '3.9'

services:
    app:
        build: .
        container_name: my-first-docker-app
        restart: unless-stopped
        ports:
        - "3001:3000"
        environment:
        - NODE_ENV=production
        depends_on:
        - db
    
    db:
        image: postgres:latest
        container_name: my-first-docker-db
        restart: unless-stopped
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=myapp
        volumes:
          - postgres_data:/var/lib/postgresql/data
        ports:
          - "5433:5432"
volumes:
    postgres_data: